#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "could not open a browser; visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "could not open a browser; visit manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# STAGES

TOTAL_STAGES=4
banner "Feugee Google Analytics setup"

stage "GA4 property and web stream"
open_url "https://analytics.google.com/"
step "Create a Google Analytics account if needed, then create a property named Feugee."
step "Choose the reporting time zone and currency used by the Agency."
step "In Admin > Data collection and modification > Data streams, add a Web stream."
step "Set the website URL to https://feugee.com and the stream name to Feugee website."
step "Open the stream's Enhanced measurement settings and turn Page views off; the site sends its own consented page_view events."
step "Copy the Measurement ID shown in the stream details. It starts with G-."
ask GA4_MEASUREMENT_ID "Paste the GA4 Measurement ID:"
if [[ ! "$GA4_MEASUREMENT_ID" =~ ^G-[A-Z0-9]+$ ]]; then
  warn "the Measurement ID must look like G-ABC1234567"
  exit 1
fi
note "This ID is used in the next stage's GTM tag only; it is not written to the repo."
pause "Web stream created and ID captured?"

stage "GTM container, tags, and triggers"
open_url "https://tagmanager.google.com/"
step "Create a Tag Manager account for Feugee and a Web container named feugee.com."
step "In the container workspace, note the container ID shown near the top; it starts with GTM-."
ask NEXT_PUBLIC_GTM_ID "Paste the GTM container ID:"
if [[ ! "$NEXT_PUBLIC_GTM_ID" =~ ^GTM-[A-Z0-9]+$ ]]; then
  warn "the container ID must look like GTM-ABC1234"
  exit 1
fi
step "In Tags, create a Google tag using Measurement ID $GA4_MEASUREMENT_ID."
step "Set its trigger to Initialization - All Pages. In the tag's configuration settings, set send_page_view to false; the site sends consented page_view events itself."
step "Create Data Layer Variables named page_location and link_url for those exact data layer keys."
step "Create four Google Analytics: GA4 Event tags, each using the same Measurement ID: page_view, contact_cta_click, email_click, phone_click. Map page_location on the page_view tag; map link_url on the three contact-event tags."
step "For each tag, create a Custom Event trigger whose event name exactly matches that tag's event name. Do not add an All Pages trigger to event tags."
step "Use Preview to test the container after the new site build is deployed. Submit > Publish and create a version when the tags are correct."
write_env NEXT_PUBLIC_GTM_ID "$NEXT_PUBLIC_GTM_ID"
set_var NEXT_PUBLIC_GTM_ID "$NEXT_PUBLIC_GTM_ID"
note "The ID is public, not a secret. The app loads GTM only after analytics consent on https://feugee.com."
pause "Container, tags, and triggers configured and published?"

stage "Search Console domain verification"
open_url "https://search.google.com/search-console/"
step "Add property > Domain, enter feugee.com, and continue."
step "Copy the TXT verification value Google provides. Keep this tab open."
open_url "https://dash.cloudflare.com/"
step "Select the feugee.com zone, then DNS > Records > Add record."
step "Choose TXT; set Name to @ and Content to Google's full verification value. Leave TTL as Auto and save."
pause "DNS record saved in Cloudflare? Return to Search Console and click Verify."
step "If verification is not immediate, wait for DNS propagation and retry Verify; do not remove the TXT record afterward."
pause "Search Console confirms the Domain property?"

stage "Submit sitemap and mark key events"
open_url "https://search.google.com/search-console/sitemaps"
step "Select the feugee.com Domain property. Enter sitemap.xml under Add a new sitemap and submit."
say "After traffic has reached GA4 and the events appear under Admin > Data display > Events:"
step "Mark contact_cta_click and email_click as key events. Leave phone_click as a regular event."
say "Before checking live tags, rebuild and redeploy the site so NEXT_PUBLIC_GTM_ID is included in its client bundle."
say "With gh authenticated, run: gh workflow run build-image.yml -R feugee/feugee"
say "Then redeploy the new latest image in Coolify. The local value is in $ENV_FILE."
pause "Sitemap submitted and setup notes understood?"

finish