#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — only the follow-up R2 cutover and production release.
# The previous VPS wizard already created env.coolify.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ENV_FILE:-env.coolify}"
TOTAL_STAGES=9

banner "Feugee — R2 cutover and production release"
warn "This flow does not rotate credentials. The attached env.coolify contained live secrets; rotate them separately before or immediately after release."

stage "R2 — connect the production custom domain"
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Open bucket feugee-assets → Settings → Custom Domains → Add."
step "Enter a hostname in the feugee.com zone (for example assets.feugee.com),"
step "Continue and review the DNS record, but do not connect it yet."
warn "This makes bucket objects publicly readable by URL. Do not enable the r2.dev development URL."
if ! confirm "Proceed with making the existing bucket publicly readable on the custom domain?"; then
  warn "Stopped before changing public bucket access."
  finish
  exit 0
fi
step "Now select Connect Domain and wait for its status to become Active."
ask R2_PUBLIC_URL "Paste the active HTTPS custom-domain base URL (no trailing slash):"
while [[ "$R2_PUBLIC_URL" != https://* ]]; do
  warn "The production URL must start with https://."
  ask R2_PUBLIC_URL "Paste the active HTTPS custom-domain base URL:"
done
R2_PUBLIC_URL="${R2_PUBLIC_URL%/}"
write_env R2_PUBLIC_URL "$R2_PUBLIC_URL"
set_var R2_PUBLIC_URL "$R2_PUBLIC_URL"
pause "Custom domain is Active and the URL is saved? Press Enter to continue."

stage "Cloudflare — cache and response headers"
open_url "https://dash.cloudflare.com"
R2_HOST="${R2_PUBLIC_URL#https://}"
R2_HOST="${R2_HOST%%/*}"
step "Select the feugee.com zone → Rules → Cache Rules → Create rule."
step "Match Hostname equals $R2_HOST; set Eligible for cache. Set Edge TTL to"
step "Ignore cache-control header and use 1 year, and Browser TTL to Override"
step "origin and 1 year. Save and deploy the rule."
say ""
step "Then Rules → Transform Rules → Modify Response Header → Create rule."
step "Match the same hostname, set the response header Cache-Control to"
step "public, max-age=31536000, immutable, then deploy the rule."
note "The Cache Rule controls Cloudflare edge TTL. The response-header rule controls the header clients see."
pause "Both rules are deployed? Press Enter to continue."

sync_secret() {
  local key="$1" prompt="$2" value
  ask_secret "$key" "$prompt"
  value="${!key}"
  write_env "$key" "$value"
  set_secret "$key" "$value"
}

stage "GitHub — configure image-build values"
open_url "https://github.com/feugee/feugee/settings/secrets/actions"
say "These are the exact values consumed by .github/workflows/build-image.yml."
say "Secret prompts are hidden and default to the value already in $ENV_FILE."
sync_secret PAYLOAD_SECRET "Payload secret (Enter keeps the existing value):"
sync_secret R2_BUCKET "R2 bucket name (Enter keeps the existing value):"
sync_secret R2_ACCOUNT_ID "R2 account ID (Enter keeps the existing value):"
sync_secret R2_ACCESS_KEY_ID "R2 access key ID (Enter keeps the existing value):"
sync_secret R2_SECRET_ACCESS_KEY "R2 secret access key (Enter keeps the existing value):"
sync_secret RESEND_API_KEY "Resend API key (Enter keeps the existing value):"
sync_secret EMAIL_FROM_ADDRESS "Email from address (Enter keeps the existing value):"
sync_secret EMAIL_FROM_NAME "Email from name (Enter keeps the existing value):"
ask NEXT_PUBLIC_SERVER_URL "Public site URL (Enter keeps the existing value):"
write_env NEXT_PUBLIC_SERVER_URL "$NEXT_PUBLIC_SERVER_URL"
set_var NEXT_PUBLIC_SERVER_URL "$NEXT_PUBLIC_SERVER_URL"
pause "GitHub values configured? Press Enter to continue."

stage "Coolify — back up production Postgres"
VPS_IP=$(_existing VPS_IP || true)
if [[ -n "$VPS_IP" ]]; then
  open_url "http://$VPS_IP:8000"
else
  say "Open your Coolify dashboard in the browser."
fi
step "Locate the production PostgreSQL resource for Feugee and create or verify"
step "a current backup using its configured backup procedure."
warn "Stop here unless you can confirm the backup completed successfully."
if ! confirm "Can you confirm a current, restorable production database backup exists?"; then
  warn "Stopped before release. Create and verify a database backup first."
  finish
  exit 1
fi

stage "Coolify — update the existing app environment"
if [[ -n "$VPS_IP" ]]; then open_url "http://$VPS_IP:8000"; fi
step "Open the existing Feugee app resource and its Environment Variables."
step "Add or update only R2_PUBLIC_URL=$R2_PUBLIC_URL. Keep the existing"
step "DATABASE_URL, R2 credentials, bucket, PAYLOAD_SECRET, and email settings."
step "Confirm the app uses ghcr.io/feugee/feugee with tag latest and port 3000."
note "Do not replace the whole environment block with this wizard; that can drop production settings."
if ! confirm "Saved the app environment and checked its image settings?"; then
  warn "Stopped before release. Save the new URL without changing other app settings."
  finish
  exit 1
fi

stage "GitHub — build the release image"
open_url "https://github.com/feugee/feugee/actions/workflows/build-image.yml"
say "Merge the reviewed application and migration changes to main, then push."
say "This starts the workflow, which builds against a temporary database and"
say "publishes latest plus a commit-tagged image; it does not touch production DB."
if confirm "Ready to push the release to main now?"; then
  step "From the repository, run: git push origin main"
  pause "Wait for Build release image to finish successfully, then press Enter."
else
  warn "Not pushing now. Finish this stage later; no production data was changed."
  finish
  exit 0
fi

stage "Coolify — deploy the new image"
if [[ -n "$VPS_IP" ]]; then open_url "http://$VPS_IP:8000"; fi
say "Wait for the GitHub image workflow to succeed before continuing."
if confirm "Is the workflow green and the production backup verified?"; then
  step "If Coolify auto-deploys latest, watch the existing app deployment."
  step "Otherwise select Redeploy on that app so it pulls the new latest image."
  step "Watch logs: pending Payload migrations → seed → server start."
  note "Migrations apply only once when pending. Do not reset or recreate the database."
  pause "Deployment is healthy at /api/health? Press Enter to verify assets."
else
  warn "Do not redeploy until the image build and database backup are confirmed."
  finish
  exit 1
fi

stage "Verify public assets"
open_url "https://feugee.com"
step "Open the Landing Page and confirm its images and videos load."
step "Copy a real image or video URL from the browser Network panel and open it"
step "in a private window; it must load without a Feugee login."
say ""
ask TEST_ASSET_URL "Paste one full public asset URL to check response headers:"
if command -v curl >/dev/null 2>&1 && [[ -n "$TEST_ASSET_URL" ]]; then
  for request_number in 1 2; do
    if ! curl -sSI --max-time 20 "$TEST_ASSET_URL" | tr -d '\r' | grep -Ei '^(HTTP/|cache-control:|cf-cache-status:)'; then
      warn "Request $request_number failed or returned no status/cache headers. Check the URL and Cloudflare rules."
    fi
  done
else
  warn "curl unavailable or no URL entered; check Cache-Control and CF-Cache-Status in browser DevTools."
fi
note "Expected: HTTP 200, Cache-Control includes immutable and max-age=31536000; second request should show a Cloudflare cache hit when cacheable."
pause "Site and anonymous asset checks passed? Press Enter to continue."

stage "Coolify — remove first-run seed credentials"
if [[ -n "$VPS_IP" ]]; then open_url "http://$VPS_IP:8000"; fi
say "After confirming the initial admin account and any intended seed content,"
say "remove SEED_DEMO, PAYLOAD_ADMIN_EMAIL, and PAYLOAD_ADMIN_PASSWORD from the"
say "Coolify app environment before its next restart or deployment."
say "Keep this local $ENV_FILE secure; it still contains credentials."
if confirm "Have you saved the admin credentials securely and removed those three Coolify variables?"; then
  note "Bootstrap variables confirmed removed."
else
  warn "Remove the bootstrap variables in Coolify before the next app restart."
fi

finish
