/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    works: Work;
    sectors: Sector;
    assets: Asset;
    clients: Client;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    works: WorksSelect<false> | WorksSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'landing-page': LandingPage;
    footer: Footer;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Generated from the title — edit only if you need a different URL.
   */
  slug?: string | null;
  subtitle?: string | null;
  /**
   * The primary visual for this Work, shown at the top of the Work Detail Page.
   */
  thumbnail?: (number | null) | Asset;
  /**
   * Shown in place of the Thumbnail as this Work's card in the Landing Page's Selected Works. Image or video. Falls back to the Thumbnail when empty.
   */
  featureVisual?: (number | null) | Asset;
  client?: string | null;
  sector?: (number | null) | Sector;
  /**
   * Year the Work was produced or released.
   */
  year?: number | null;
  /**
   * The project lead responsible for this Work.
   */
  associate?: string | null;
  expertise?: string[] | null;
  /**
   * Feugee's own staff credited on this Work.
   */
  projectTeam?: string[] | null;
  /**
   * People outside Feugee credited on this Work.
   */
  collaborators?: string[] | null;
  testimonials?:
    | {
        name: string;
        job?: string | null;
        company?: string | null;
        testimony: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The content of the Work Detail Page, in sidebar order.
   */
  sections?:
    | {
        title: string;
        layouts?:
          | (
              | {
                  /**
                   * A single item at full width.
                   */
                  items?:
                    | (
                        | {
                            title: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'title';
                          }
                        | {
                            entries?:
                              | {
                                  title: string;
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'titled-text';
                          }
                        | {
                            entries?:
                              | {
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'text';
                          }
                        | {
                            asset: number | Asset;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'asset';
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'one-column';
                }
              | {
                  /**
                   * Two items side by side.
                   */
                  items?:
                    | (
                        | {
                            title: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'title';
                          }
                        | {
                            entries?:
                              | {
                                  title: string;
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'titled-text';
                          }
                        | {
                            entries?:
                              | {
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'text';
                          }
                        | {
                            asset: number | Asset;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'asset';
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'two-column';
                }
              | {
                  /**
                   * Three items side by side.
                   */
                  items?:
                    | (
                        | {
                            title: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'title';
                          }
                        | {
                            entries?:
                              | {
                                  title: string;
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'titled-text';
                          }
                        | {
                            entries?:
                              | {
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'text';
                          }
                        | {
                            asset: number | Asset;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'asset';
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'three-column';
                }
              | {
                  /**
                   * Item 1 spans two rows on the left; items 2 and 3 stack on the top and bottom right.
                   */
                  items?:
                    | (
                        | {
                            title: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'title';
                          }
                        | {
                            entries?:
                              | {
                                  title: string;
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'titled-text';
                          }
                        | {
                            entries?:
                              | {
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'text';
                          }
                        | {
                            asset: number | Asset;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'asset';
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'feature-left';
                }
              | {
                  /**
                   * Item 1 spans two rows on the right; items 2 and 3 stack on the top and bottom left.
                   */
                  items?:
                    | (
                        | {
                            title: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'title';
                          }
                        | {
                            entries?:
                              | {
                                  title: string;
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'titled-text';
                          }
                        | {
                            entries?:
                              | {
                                  text: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'text';
                          }
                        | {
                            asset: number | Asset;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'asset';
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'feature-right';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images and videos referenced by site content. Up to 100 MB each.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: number;
  /**
   * Describes the image or video for screen readers and search engines.
   */
  alt: string;
  /**
   * Image shown before the video plays. Pick one with the same frame size as the video — it fixes the video's slot in grids and the masonry.
   */
  poster?: (number | null) | Asset;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The industries Works are filed under — drives filtering on the Works Page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  /**
   * Generated from the name — edit only if you need a different URL.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The external companies Works are made for — drives the Client Marquee on the Landing Page. Drag order is the marquee order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Image only — SVG especially welcome. The marquee applies its own colour treatment at render time.
   */
  logo: number | Asset;
  /**
   * Optional link to the client's website.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'assets';
        value: number | Asset;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  thumbnail?: T;
  featureVisual?: T;
  client?: T;
  sector?: T;
  year?: T;
  associate?: T;
  expertise?: T;
  projectTeam?: T;
  collaborators?: T;
  testimonials?:
    | T
    | {
        name?: T;
        job?: T;
        company?: T;
        testimony?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        layouts?:
          | T
          | {
              'one-column'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          title?:
                            | T
                            | {
                                title?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'titled-text'?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      title?: T;
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          text?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          asset?:
                            | T
                            | {
                                asset?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              'two-column'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          title?:
                            | T
                            | {
                                title?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'titled-text'?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      title?: T;
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          text?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          asset?:
                            | T
                            | {
                                asset?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              'three-column'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          title?:
                            | T
                            | {
                                title?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'titled-text'?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      title?: T;
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          text?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          asset?:
                            | T
                            | {
                                asset?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              'feature-left'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          title?:
                            | T
                            | {
                                title?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'titled-text'?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      title?: T;
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          text?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          asset?:
                            | T
                            | {
                                asset?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              'feature-right'?:
                | T
                | {
                    items?:
                      | T
                      | {
                          title?:
                            | T
                            | {
                                title?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'titled-text'?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      title?: T;
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          text?:
                            | T
                            | {
                                entries?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          asset?:
                            | T
                            | {
                                asset?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  alt?: T;
  poster?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The content of the site's front page, section by section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  /**
   * The full-screen opening: the title and its rotating words over a slider of videos.
   */
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * The fixed opening word of the title's second line — "Into" by default.
     */
    leadInWord?: string | null;
    /**
     * The button in the Hero's bottom-right. Without a URL it scrolls to the content below the Hero; without a label it does not render.
     */
    scrollCue?: {
      label?: string | null;
      /**
       * Internal path or external URL. Leave empty to scroll to the content below the Hero.
       */
      url?: string | null;
    };
    /**
     * The words that cycle as the title's last word, in order. A single word renders statically.
     */
    rotatingWords?:
      | {
          word: string;
          id?: string | null;
        }[]
      | null;
    slides?:
      | {
          /**
           * Video only. Set the poster on the Asset itself — it is the slide's preview frame.
           */
          video: number | Asset;
          id?: string | null;
        }[]
      | null;
  };
  whoWeAre?: {
    heading?: string | null;
    description?: string | null;
  };
  /**
   * Proof figures shown together — e.g. 55+ / Videos.
   */
  stats?:
    | {
        /**
         * The figure — e.g. "55+" or "35+M".
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The heading above the Client Marquee.
   */
  clientsHeading?: string | null;
  /**
   * Works featured on the Landing Page, in display order.
   */
  selectedWorks?: (number | Work)[] | null;
  /**
   * The heading above the Selected Works.
   */
  selectedWorksHeading?: string | null;
  /**
   * Endorsements of the agency, shown below Selected Works in two counter-scrolling columns.
   */
  testimonials?: {
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          name: string;
          job?: string | null;
          company?: string | null;
          testimony: string;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The content of the Footer at the bottom of every public page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The closing call-to-action at the top of the Footer: eyebrow, headline, body copy, and up to two buttons.
   */
  cta?: {
    /**
     * The small line above the headline — e.g. "Free 20-min intro call".
     */
    eyebrow?: string | null;
    headline?: string | null;
    body?: string | null;
    /**
     * The button label — e.g. "Work with us".
     */
    actionLabel?: string | null;
    /**
     * Where the button points — internal path or external URL. Without it the button renders inert.
     */
    actionUrl?: string | null;
    /**
     * The second button's label — e.g. "See our works". The button renders only when this is filled.
     */
    secondaryActionLabel?: string | null;
    /**
     * Where the second button points. Without it the button renders inert, like the primary.
     */
    secondaryActionUrl?: string | null;
  };
  about?: {
    heading?: string | null;
    description?: string | null;
  };
  /**
   * Heading above the Other Works cards.
   */
  otherWorksHeading?: string | null;
  /**
   * Works shown as cards beside the About blurb, in display order.
   */
  otherWorks?: (number | Work)[] | null;
  /**
   * Heading above the menu links.
   */
  menuHeading?: string | null;
  menuLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    heading?: string | null;
    /**
     * The call-to-action label — e.g. "Book a Call". Links out when a URL is set.
     */
    callToAction?: string | null;
    callToActionUrl?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * The pinned location label in the bottom bar.
   */
  location?: string | null;
  /**
   * Social media profiles in the bottom bar — the platform picks the icon.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'behance' | 'linkedin' | 'pinterest' | 'dribbble' | 'contra';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who holds the copyright in the bottom bar — e.g. "Feugee".
   */
  copyrightName?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        leadInWord?: T;
        scrollCue?:
          | T
          | {
              label?: T;
              url?: T;
            };
        rotatingWords?:
          | T
          | {
              word?: T;
              id?: T;
            };
        slides?:
          | T
          | {
              video?: T;
              id?: T;
            };
      };
  whoWeAre?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  clientsHeading?: T;
  selectedWorks?: T;
  selectedWorksHeading?: T;
  testimonials?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              job?: T;
              company?: T;
              testimony?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        actionLabel?: T;
        actionUrl?: T;
        secondaryActionLabel?: T;
        secondaryActionUrl?: T;
      };
  about?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  otherWorksHeading?: T;
  otherWorks?: T;
  menuHeading?: T;
  menuLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        callToAction?: T;
        callToActionUrl?: T;
        email?: T;
        phone?: T;
      };
  location?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightName?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}